"""add execution timeout to jobs

Revision ID: 0b4f74711670
Revises: 571d4f79a4a6
Create Date: 2026-02-28 23:36:32.366745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4f74711670'
down_revision: Union[str, Sequence[str], None] = '571d4f79a4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('max_execution_seconds', sa.Integer(), nullable=False, server_default="300"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_execution_seconds')
    # ### end Alembic commands ###
