"""add retry control to jobs

Revision ID: 571d4f79a4a6
Revises: f9adc73addd6
Create Date: 2026-02-26 23:25:37.521744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '571d4f79a4a6'
down_revision: Union[str, Sequence[str], None] = 'f9adc73addd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.add_column('job_executions', sa.Column('progress', sa.Integer(), nullable=False))
    op.drop_column('job_executions', 'progess')
    op.drop_column('job_executions', 'attemt_number')
    op.add_column('jobs', sa.Column('max_retries', sa.Integer(), nullable=False, server_default="3"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_retries')
    op.add_column('job_executions', sa.Column('attemt_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('job_executions', sa.Column('progess', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('job_executions', 'progress')
    op.drop_column('job_executions', 'attempt_number')
    # ### end Alembic commands ###
