"""add execution duration

Revision ID: 7ed659e90a9c
Revises: 9df973d97fe7
Create Date: 2026-02-25 19:03:13.353238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed659e90a9c'
down_revision: Union[str, Sequence[str], None] = '9df973d97fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_executions', 'duration_seconds')
    # ### end Alembic commands ###
