"""add recovery attempts to jobs

Revision ID: a4ad870b6133
Revises: 25e825769f47
Create Date: 2026-02-24 16:58:24.552728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ad870b6133'
down_revision: Union[str, Sequence[str], None] = '25e825769f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'jobs',
        sa.Column(
            'recovery_attempts',
            sa.Integer(),
            nullable=False,
            server_default="0"
        )
    )
    op.alter_column(
        'jobs',
        'recovery_attempts',
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'recovery_attempts')
    # ### end Alembic commands ###
