"""add execution progress

Revision ID: f9adc73addd6
Revises: 7ed659e90a9c
Create Date: 2026-02-25 19:28:35.412944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9adc73addd6'
down_revision: Union[str, Sequence[str], None] = '7ed659e90a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_executions', sa.Column('progess', sa.Integer(), nullable=False))
    op.add_column('job_executions', sa.Column('current_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_executions', 'current_step')
    op.drop_column('job_executions', 'progess')
    # ### end Alembic commands ###
